### ISSUE TITLE
Restaurant: confusing navigation after updating password

### ISSUE THREAD

**Issue by joserambla** [miguelespada/diinner#1]
Navigation after update is not the restaurant administration page but the home page (when you can choose Admin, Restaurante or User)

**Comment by miguelespada** [comment]
Know issue in Devise.
http://stackoverflow.com/questions/4264750/devise-logging-out-automatically-after-password-change

**Comment by miguelespada** [comment]
It's not a very used feature and it's the recommend behavior for security reasons. So we will not fix it.
