### ISSUE TITLE
User: sign up with Google produces error

### ISSUE THREAD

**Issue by joserambla** [miguelespada/diinner#12]
Steps: 
- Empty DB
- Sign up with Google account
- app/model/user.rb - line 110: 
      Object "birth" is nil but method "year" is trying to be used in this object.

**Comment by joserambla** [comment]
The same happens if I first sing up with a FB account and then navigate to Preferences page

**Comment by miguelespada** [comment]
My mistake, I forgot to set a default age

I fact app users will be force to add the birth date, so no worries.
