### ISSUE TITLE
Restaurant: edit menu - problems with blank fields

### ISSUE THREAD

**Issue by joserambla** [miguelespada/diinner#14]
When editing a menu, leaving blank fields that previously had data won't affect the menu. It means that it is not possible leave blank any of the optional fields and it is possible to save it leaving the name blank, which is mandatory (although it won't delete it). A form control should be implemented for this last case.

**Comment by miguelespada** [comment]
Patched with an error message, but it's not the proper way. 
Form should display "validation messages"
