### ISSUE TITLE
User: new reservation after cancellation in the same day

### ISSUE THREAD

**Issue by joserambla** [miguelespada/diinner#17]
Steps to reproduce: 
- There is a table available for tomorrow. 
- I reserve a chair. 
- I cancel. 
- I search again with the same criteria. 
Result: 
No modification to the table has been done, but I get a "no diinners matching your search" message. It doesn't matter if I try with different menus (20 or 40 euros)

**Comment by miguelespada** [comment]
I cannot reproduce this bug. 
I works for me.
