### ISSUE TITLE
Restaurant: create table - situation when the recurrence date is lower than the first date not controlled

### ISSUE THREAD

**Issue by joserambla** [miguelespada/diinner#19]
While creating a new table:
- Enter a different date than today 
- Not modify the Repeat every week until field, which is prefilled with today date.
Result:
The application navigates to the tables list not complaining and saying that "table(s) were created" but actually not creating the new table. Repeat every week until should be blank until a date has been selected and then automatically take the same date.

**Comment by miguelespada** [comment]
Added better notification
