### ISSUE TITLE
System: process reservations cancelling tables that should not be cancelled

### ISSUE THREAD

**Issue by joserambla** [miguelespada/diinner#43]
Executing this seed: 

def full_table_for_today
  delete_all
  create_basic_context

  
  reservation =  FactoryGirl.create(:reservation, user: @he, table: @restaurant.tables.first, date: 2.days.ago)
  reservation.companies.create(age: 30, gender: :male)
  reservation.companies.create(age: 30, gender: :male)
  reservation.save!

  reservation =  FactoryGirl.create(:reservation, user: @she, table: @restaurant.tables.first, date: 1.days.ago)
  reservation.companies.create(age: 30, gender: :female)
  reservation.companies.create(age: 30, gender: :female)
  reservation.save!

end

After processing tables, the system cancels the table

**Comment by miguelespada** [comment]
Not a bug.
You need to add "Valid payment information", otherwise it's cancelled because the payment fails

  @he.update_customer_information!(Stripe::Token.create(valid_card).id)
  @she.update_customer_information!(Stripe::Token.create(valid_card).id)

The corrected seed was added
